version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: python3 -m src.main

  frontend:
    build: ./frontend/stock-ui
    ports:
      - "3000:80"
